image: cbenz/dbnomics-gitlab-ci-docker:latest

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt -qq --yes update

  # Install fetcher dependencies.
  - '[ -f requirements.txt ] && pip3 install --requirement requirements.txt'

  # Install ssh-agent if not already installed, it is required by Docker.
  - 'which ssh-agent || apt -qq --yes install openssh-client'

  # Run ssh-agent (inside the build environment).
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store.
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # Add the SSH keys of remote Git servers, to disable host key checking questions.
  - mkdir -p ~/.ssh
  - ssh-keyscan -t rsa git.nomics.world >> ~/.ssh/known_hosts

  - git config --global push.default simple
  - git config --global user.email "{provider_slug}-fetcher@db.nomics.world"
  - git config --global user.name "{provider_slug} fetcher"

  # Display current date to ease post-mortem debugging.
  - date

variables:
  # Can be "download" or "convert"
  JOB: convert

job:
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - set -x
    - |
      if [ "${JOB}" == "download" ]; then
        time git clone --quiet --depth=1 git@git.nomics.world:dbnomics-source-data/{provider_slug}-source-data.git
        cd {provider_slug}-source-data
        time find -not -path "./.git/*" -not -name ".git" -delete
        cd ..
        time python3 download.py {provider_slug}-source-data
        cd {provider_slug}-source-data
        time git add -A
        time git commit -m "New fetch" --quiet || echo "Nothing to commit"
        time git push || echo "Nothing to push"
      fi
    - |
      if [ "${JOB}" == "convert" ]; then
        time git clone --quiet --depth=1 https://git.nomics.world/dbnomics-source-data/{provider_slug}-source-data.git
        time git clone --quiet --depth=1 git@git.nomics.world:dbnomics-json-data/{provider_slug}-json-data.git
        cd {provider_slug}-json-data
        time find -not -path "./.git/*" -not -name ".git" -delete
        cd ..
        time python3 convert.py {provider_slug}-source-data {provider_slug}-json-data
        cd {provider_slug}-json-data
        time git add -A
        time git commit -m "New conversion" --quiet || echo "Nothing to commit"
        time git push || echo "Nothing to push"
      fi